server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: member
          predicates:
            - Path=/member/**
          uri: http://127.0.0.1:8001
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true      #允许携带cookie
            allowedHeaders: '*'         #允许的头
            allowedMethods: '*'         #允许的请求方式
            allowedOriginPatterns: '*'  #允许的请求来源
            maxAge: 3600                #会先发一个option请求来判断这个post请求是否可用

